name: Publish artifact

# Publish on a push
on:
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -f source/pom.xml package
    - name: Publish Artifact
      uses: samuelmeuli/action-maven-publish@v1
      with:
        server_id: aerius-nexus
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        directory: source/
        # Tests are already run in the Build step, no use running them again
        maven_args: -DskipTests
